artifact_root: ./artifacts

data_ingestion:
 root_dir: artifacts/data_ingestion
 source_URL : https://github.com/happii2k/dataset.git
 local_data_file: artifacts/data_ingestion/data.zip
 unzip_dir: artifacts/data_ingestion

 